export const SET_USER = 'SET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const SET_USER_EMAIL = 'SET_USER_EMAIL';

export const SET_SHOP = 'SET_SHOP';
export const UPDATE_SHOP = 'UPDATE_SHOP';
export const DELETE_SHOP_PERSONNEL = 'DELETE_SHOP_PERSONNEL';
export const DELETE_SHOP = 'DELETE_SHOP';


export const SET_PERSONNEL = 'SET_PERSONNEL';
export const DELETE_PERSONNEL = 'DELETE_PERSONNEL';
export const SET_PERSONNEL_SERVICES = 'SET_PERSONNEL_SERVICES';

export const SET_RESERVE_INFO = 'SET_RESERVE_INFO';
export const DELETE_RESERVE_INFO = 'DELETE_RESERVE_INFO';

export const SET_RESERVE = 'SET_RESERVE';
export const DELETE_RESERVE = 'DELETE_RESERVE';

export const SET_EDIT = 'SET_EDIT';
export const DELETE_EDIT = 'DELETE_EDIT';

export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
export const UPDATE_NOTIFICATION_COUNT = 'UPDATE_NOTIFICATION_COUNT';